# SwiftLint configuration

disabled_rules: # rules you want to turn off
  - trailing_whitespace
  - line_length # we handle this with rulers in Cursor
  - force_cast   # allow only if absolutely needed

opt_in_rules: # extra good rules
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
  - force_unwrapping

included:
  - MileTracker

excluded:
  - Carthage
  - Pods
  - .build
  - .git

# line_length configuration removed since rule is disabled

identifier_name:
  min_length: 3
  excluded:
    - id
    - URL
    - x
    - y

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 40
  error: 80

cyclomatic_complexity:
  warning: 10
  error: 20
